### ISSUE TITLE
Auth Step

### ISSUE THREAD

**Issue by adityosnrost** [TykTechnologies/tyk-plugin-demo-python#1]
Hi,

I would like to use my own Auth service on every request. I found that by creating plugin is the best way to do it. I am just curious, How can I return an error directly after pre function ?

For example:

1. User access api
2. Plugin check the token that sent along with the api request
3 if it is false, then return error directly to user as Error HTTP 401 without processing into the proxy url.

Thanks

**Comment by mvdan** [comment]
@matiasinsaurralde

**Comment by lonelycode** [comment]
Hi, this might be best posted on our community forum as it is not a bug or a feature request.
